zk:
  image: mesoscloud/zookeeper:3.4.6-ubuntu-14.04
  environment:
     - MYID=1
     - SERVERS=localhost

master:
  image: mesosphere/mesos-master:0.28.1-2.0.20.ubuntu1404
  privileged: true
  ports:
    - "5050:5050"
  links:
    - "zk:zookeeper"
  environment:
    - MESOS_HOSTNAME=localhost
    - MESOS_QUORUM=1
    - MESOS_ZK=zk://zookeeper:2181/mesos

slave:
  image: mesosphere/mesos-slave-dind:0.2.4_mesos-0.27.2_docker-1.8.2_ubuntu-14.04.4
  privileged: true
  links:
    - "master:master"
    - "zk:zookeeper"
  ports:
    - "5051:5051"
  dns:
    - "8.8.8.8"
    - "8.8.4.4"
  environment:
    - MESOS_PORT=5051
    - MESOS_HOSTNAME=192.168.99.100
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_ISOLATOR=cgroups/cpu, cgroups/mem
    - MESOS_LOG_DIR=var/log
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD=90secs
    - MESOS_DOCKER_STOP_TIMEOUT=60secs
    - MESOS_RESOURCES=cpus:4;mem:1280;disk:25600;ports(*):[12000-12999]

marathon:
  image: mesosphere/marathon:v0.15.2
  ports:
    - "8080:8080"
  links:
    - "zk:zookeeper"
  environment:
    - MARATHON_MASTER=zk://zookeeper:2181/mesos
    - MARATHON_ZK=zk://zookeeper:2181/marathon

# chronos:
#   image: mesoscloud/chronos:2.4.0-ubuntu-14.04
#   links:
#     - "zk:zookeeper"
#   ports:
#     - "4400:4400"
#   environment:
#    - CHRONOS_HTTP_PORT=4400
#    - CHRONOS_MASTER=zk://zookeeper:2181/mesos
#    - CHRONOS_ZK_HOSTS=zookeeper:2181
#
# bamboo:
#   image: luprzybyl/bamboo:0.2.15
#   links:
#     - "zk:zookeeper"
#   environment:
#    - BAMBOO_ZK_HOST=zookeeper:2181
#    - BAMBOO_ZK_PATH=/bamboo
#    - BAMBOO_DOCKER_AUTO_HOST=true
